### ISSUE TITLE
Efficiency warning

### ISSUE THREAD

**Issue by vidstige** [GregTJ/stable-fluids#3]
I just cloned and run this, installing latest numpy and scipy. I'm getting the following warning:

`SparseEfficiencyWarning: splu requires CSC matrix format`

Perhaps this blazing fast simulation can be speed up even further if whatever function is emitting this warning is given a sparse csc matrix instead?

**Comment by GregTJ** [comment]
Forgot to close this but it has been corrected. However, simulation times should be unaffected as it only relates to the generation of initial operator matrix.

**Comment by GregTJ** [comment]
Forgot to close this but it has been corrected. However, simulation times should be unaffected as this bug only relates to the initialization of the operator matrix.
